### ISSUE TITLE
support for embedFS

### ISSUE THREAD

**Issue by jritsema** [karelbilek/template-parse-recursive#1]
Hey there.  Thanks for this project!  Any idea if something like this exists for templates loaded using `//go:embed`?  It looks like `template.ParseFS()` calls `fs.Glob()` which doesn't support recursion.

**Comment by karelbilek** [comment]
Hey! Thanks!

When I started making it, the FS abstraction either was not there, or was new and I didn't know about it. I will look at it later.

**Comment by jritsema** [comment]
Hey.  I ended up solving like this.

```go
// recursively parses all templates in the FS with the given extension
// filepaths are used as template names to support duplicate file names
func templateParseFSRecursive(templates fs.FS, ext string, funcMap template.FuncMap) (*template.Template, error) {
	root := template.New("")
	err := fs.WalkDir(templates, "templates", func(path string, d fs.DirEntry, err error) error {
		if !d.IsDir() && strings.HasSuffix(path, ext) {
			if err != nil {
				return err
			}
			b, err := fs.ReadFile(templates, path)
			if err != nil {
				return err
			}
			//name the template based on the file path (excluding the root)
			parts := strings.Split(path, string(os.PathSeparator))
			name := strings.Join(parts[1:], string(os.PathSeparator))
			t := root.New(name).Funcs(funcMap)
			_, err = t.Parse(string(b))
			if err != nil {
				return err
			}
		}
		return nil
	})
	return root, err
}
```

**Comment by karelbilek** [comment]
I am solving it similarly, but I want to keep the ability to use symlinks, as I use this in my case and fs.WalkDir does NOT traverse into dir symlinks

**Comment by karelbilek** [comment]
@jritsema latest master can now use embed.FS

You are welcome to use it, or not, as you wish :D I'm happy someone found it useful at least for a bit, I made it to scratch my own itch
