### ISSUE TITLE
Can't seem to add funcs

### ISSUE THREAD

**Issue by pocket5s** [karelbilek/template-parse-recursive#2]
Trying to add a custom function using the below example. Whenever the HTMLParse is called it says the function isn't define.

`	
       base := template.New("templates").Funcs(template.FuncMap{
		"formatDate": formatDate,
	})
	t, err := recurparse.HTMLParse(
		base,
		"www",
		"*.html",
	)

	if err != nil {
		panic(err)
	}
`

**Comment by karelbilek** [comment]
Ah. It’s possible I don’t pass that correctly. Will see later this week

**Comment by karelbilek** [comment]
Sorry for late reply. Now I have time for this

**Comment by karelbilek** [comment]
ugh it was stupid :D fixing it

**Comment by karelbilek** [comment]
Fixed in 3616296f058a4fc41824d133c5adcc3c164317b0

**Comment by karelbilek** [comment]
Fixed, added tests
